### ISSUE TITLE
Doesn't set channel

### ISSUE THREAD

**Issue by rhagelstrom** [bmos/FG-Forge-Updater#23]
Updater doesn't set the channel any more. I also had problems with updating the readme
   env:
          FG_USER_NAME: ${{ vars.FG_USER_NAME }}
          FG_USER_PASS: ${{ secrets.FG_USER_PASS }}
          FG_ITEM_ID: ${{ vars.FG_ITEM_ID }}
          FG_UL_FILE: ${{ github.event.repository.name }}${{ env.EXTENSION }}
          FG_README_UPDATE: 'TRUE'
          FG_RELEASE_CHANNEL: 'LIVE'

If I have the env FG_README_UPDATE it doesn't seem to update the readme. if I omit it then it does. If I set the release channel to LIVE or I omit it, it stays in no assigned channel

**Comment by bmos** [comment]
FG_README_UPDATE: 'TRUE' is not needed, although it shouldn't be being detected as FALSE.

**Comment by bmos** [comment]
What release are you targeting?
