### ISSUE TITLE
Forge description page not updated

### ISSUE THREAD

**Issue by rhagelstrom** [bmos/FG-Forge-Updater#8]
Completely blew away my for item page. Its for Better Combat Effects though and that MD is lengthy

**Comment by bmos** [comment]
Got it, I'll test with that. Thanks!

**Comment by rhagelstrom** [comment]
Ok so it looks like the readme needs to be in the ext. When I did that it did update but it doesn't like do the tables or something right so it's all a wall of gibberish

**Comment by bmos** [comment]
Ah, I didn't think to try it with a table.
Having no README was supposed to cause it to skip that feature but I guess not!
I'll add a test for that.

**Comment by rhagelstrom** [comment]
FWIW I used to be able to copy the markdown as displayed on GitHub and paste it onto the forge for BCE but at some point over the last 4-6 months or so I think the forge just errors out processing the table and so the paste ends up being incomplete when saved.

**Comment by bmos** [comment]
So probably should "bin" the content and insert it into the text box in smaller bunches of characters.

**Comment by bmos** [comment]
I looked into this a bit this morning and it's not length related.
The entire README.md file for BCE was inserted. The only issues were with tables.
It appears that the library I'm using requires an (included) extension to handle tables.
https://python-markdown.github.io/extensions/tables/#tables

I'll give it a shot now.

**Comment by bmos** [comment]
Yeah, that fixed most of it.
But the tables that had images in them are broken because the image links in your README.md file are relative (rather than including the github url).

It's also still not handling the `\` as new-line, either. I'll see what other extensions exist for the parser library.

**Comment by bmos** [comment]
The table issue is not because of the images
![image](https://github.com/bmos/FG-Forge-Updater/assets/1916835/fb588d23-9c3e-41cd-9d3b-3fd92c83daee)

**Comment by bmos** [comment]
It was a difference in how GitHub and the parser interpret your README.

Before `| Name| Default | Options | Notes | Ruleset|` and `|Icon|Shorthand|Description|` (or any other table) you need an empty line. All your other tables have that, but those two do not.

![image](https://github.com/bmos/FG-Forge-Updater/assets/1916835/fb8410be-4849-4ce5-927b-02f18a2ac9d8)
